
name: terraform

on:
  push:
    branches:
      - gopi
  pull_request:
    branches:
      - gopi

jobs:
  Terraform:
    name: "terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET.ACCESS_KEY}}
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.11
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Terraform check
        run: terraform validate

      - name: Terraform Formate
        run: terraform fmt

      - name: Terraform plan
        run: terraform plan -var-file="dev.tfvars"
        
      - name: Terraform apply
        run: terraform apply -var-file="dev.tfvars"  -auto-approve

      - name: Terraform destroy
        run: terraform destroy -var-file="dev.tfvars"  -auto-approve
